/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.creerapplication;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author lenov
 */
public class EcolFormApp extends javax.swing.JFrame {

    private static EcolFormApp instance;

    /**
     * Creates new form EcolFormApp
     */
    public EcolFormApp() {
        initComponents();
    }

    //methode instance pour singleton
    static EcolFormApp getInstance() {
        if (instance == null) {
            instance = new EcolFormApp();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddEtudMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AddFiliereMenuItem = new javax.swing.JMenuItem();
        ModifyFiliereMenuItem = new javax.swing.JMenuItem();
        DeleteFiliereMenuItem = new javax.swing.JMenuItem();
        listeFiliereMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ECOLE DE FORMATION POLYTECHNIQUE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 290, 930, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lenov\\Desktop\\fotolia.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, 0, 1400, 630);

        jMenu1.setText("Etudiants");

        AddEtudMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AddEtudMenuItem.setText("Add Etudiant");
        AddEtudMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEtudMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(AddEtudMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Liste Etudiant Filieres");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Liste Etudiant Niveau");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Liste Etudiant");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Filieres");

        AddFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AddFiliereMenuItem.setText("Add Filiere");
        AddFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AddFiliereMenuItem);

        ModifyFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ModifyFiliereMenuItem.setText("Modify Filiere");
        ModifyFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ModifyFiliereMenuItem);

        DeleteFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DeleteFiliereMenuItem.setText("Delete Filiere");
        DeleteFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(DeleteFiliereMenuItem);

        listeFiliereMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        listeFiliereMenuItem.setText("ListeFiliere");
        listeFiliereMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeFiliereMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(listeFiliereMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEtudMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEtudMenuItemActionPerformed
        System.out.println("Clique sur add Etudiant");
        JPanel contenuFenetre = new GestionDesEtudiants();
        //limiter la fenetre toujours mettre ca
        JScrollPane scrollPane = new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_AddEtudMenuItemActionPerformed

    private void AddFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFiliereMenuItemActionPerformed
        System.out.println("Clique sur add Filiere");
        JPanel contenuFenetre = new GestionDesFilieres();
        //limiter la fenetre toujours mettre ca
        JScrollPane scrollPane = new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_AddFiliereMenuItemActionPerformed

    private void ModifyFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyFiliereMenuItemActionPerformed
        System.out.println("Clique sur liste modify Filiere ");
       Modify contenuFenetre=new Modify();
        JScrollPane scrollPane=new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_ModifyFiliereMenuItemActionPerformed

    private void DeleteFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFiliereMenuItemActionPerformed
        System.out.println("Clique sur  delete Filiere ");
        JPanel contenuFenetre = new GestionDesFilieres();
        setContentPane(contenuFenetre);
        revalidate();
        repaint();
    }//GEN-LAST:event_DeleteFiliereMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListeEtudFiliere contenuFenetre = new ListeEtudFiliere() ;
        JScrollPane scrollPane = new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Listeretudiant contenuFenetre = new Listeretudiant();
        JScrollPane scrollPane = new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void listeFiliereMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeFiliereMenuItemActionPerformed
       ListeFiliere contenu = new ListeFiliere();
        JScrollPane scrollPane = new JScrollPane(contenu);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_listeFiliereMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListEtudNiv contenuFenetre = new ListEtudNiv() ;
        JScrollPane scrollPane = new JScrollPane(contenuFenetre);
        setContentPane(scrollPane);
        revalidate();
        repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcolFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcolFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcolFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcolFormApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcolFormApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddEtudMenuItem;
    private javax.swing.JMenuItem AddFiliereMenuItem;
    private javax.swing.JMenuItem DeleteFiliereMenuItem;
    private javax.swing.JMenuItem ModifyFiliereMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem listeFiliereMenuItem;
    // End of variables declaration//GEN-END:variables
}
