/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.creerapplication;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sn.ugb.ipsl.DataAccessObject.NomFDataInvalid;
import sn.ugb.ipsl.DataAccessObject.DbaseUtils;
import sn.ugb.ipsl.entity.Filiere;
import sn.ugb.ipsl.service.FiliereServiceImplem;
import sn.ugb.ipsl.service.InterfaceFiliereService;

/**
 *
 * @author lenov
 */
public class GestionDesFilieres extends javax.swing.JPanel {

    private InterfaceFiliereService filiereService = new FiliereServiceImplem();

    /**
     * Creates new form GestionDesFilieres
     */
    public GestionDesFilieres() {
        initComponents();
        nomfErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Licence1RadioButton = new javax.swing.JRadioButton();
        Licence2RadioButton = new javax.swing.JRadioButton();
        Licence3RadioButton = new javax.swing.JRadioButton();
        Masteur1RadioButton = new javax.swing.JRadioButton();
        Masteur2RadioButton = new javax.swing.JRadioButton();
        nomfErrorLabel = new javax.swing.JLabel();
        ExitFiliereButton = new javax.swing.JButton();
        deleteFiliereButton = new javax.swing.JButton();
        saveFiliereButton = new javax.swing.JButton();
        cancelFiliereButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter-Filiere:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NomF:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("CREER LES NIVEAUX:");

        Licence1RadioButton.setText("L1");
        Licence1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Licence1RadioButtonActionPerformed(evt);
            }
        });

        Licence2RadioButton.setText("L2");
        Licence2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Licence2RadioButtonActionPerformed(evt);
            }
        });

        Licence3RadioButton.setText("L3");
        Licence3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Licence3RadioButtonActionPerformed(evt);
            }
        });

        Masteur1RadioButton.setText("M1");
        Masteur1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masteur1RadioButtonActionPerformed(evt);
            }
        });

        Masteur2RadioButton.setText("M2");
        Masteur2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masteur2RadioButtonActionPerformed(evt);
            }
        });

        nomfErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        nomfErrorLabel.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Licence3RadioButton)
                                        .addGap(49, 49, 49)
                                        .addComponent(Masteur1RadioButton))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Licence1RadioButton)
                        .addGap(29, 29, 29)
                        .addComponent(Licence2RadioButton)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Masteur2RadioButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(nomfErrorLabel)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomfErrorLabel))
                .addGap(137, 137, 137)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Licence1RadioButton)
                    .addComponent(Licence2RadioButton)
                    .addComponent(Licence3RadioButton)
                    .addComponent(Masteur1RadioButton)
                    .addComponent(Masteur2RadioButton))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        ExitFiliereButton.setText("Exit");
        ExitFiliereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitFiliereButtonActionPerformed(evt);
            }
        });

        deleteFiliereButton.setText("Delete");
        deleteFiliereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFiliereButtonActionPerformed(evt);
            }
        });

        saveFiliereButton.setText("SaveFiliere");
        saveFiliereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFiliereButtonActionPerformed(evt);
            }
        });

        cancelFiliereButton1.setText("cancel");
        cancelFiliereButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFiliereButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelFiliereButton1)
                    .addComponent(deleteFiliereButton))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitFiliereButton)
                    .addComponent(saveFiliereButton))
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelFiliereButton1)
                            .addComponent(ExitFiliereButton))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteFiliereButton)
                    .addComponent(saveFiliereButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Masteur1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masteur1RadioButtonActionPerformed
        Masteur2RadioButton.setSelected(true);
        Licence1RadioButton.setSelected(true);
        Licence2RadioButton.setSelected(true);
        Licence3RadioButton.setSelected(true);
        Masteur1RadioButton.setSelected(true);

    }//GEN-LAST:event_Masteur1RadioButtonActionPerformed

    private void Masteur2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masteur2RadioButtonActionPerformed
        Masteur2RadioButton.setSelected(true);
        Licence1RadioButton.setSelected(true);
        Licence2RadioButton.setSelected(true);
        Licence3RadioButton.setSelected(true);
        Masteur1RadioButton.setSelected(true);

    }//GEN-LAST:event_Masteur2RadioButtonActionPerformed

    private void deleteFiliereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFiliereButtonActionPerformed

        try {
            Connection c = DbaseUtils.getConnection();
            Statement st = c.createStatement();

            if (JOptionPane.showConfirmDialog(null, "Attention vous allez supprimer une Filiere,est ce que vousen etes sure?", "supprimer Filiere", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (nameTextField.getText().length() != 0) {
                    st.executeUpdate("Delete From Filiere where nomF=" + nameTextField.getText());
                    JOptionPane.showMessageDialog(null, "Suppression Reussie");
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez Remplir le Champ nom");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(GestionDesFilieres.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteFiliereButtonActionPerformed

    private void saveFiliereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFiliereButtonActionPerformed
        String nomF = nameTextField.getText();
       // Integer id = Integer.parseInt(idf);
        Filiere f = new Filiere();
        f.setNomF(nomF);

        if (nomF != null || nomF.isBlank()) {
            JOptionPane.showMessageDialog(null, "insertion Reussie");
        } else {
            JOptionPane.showMessageDialog(null, "insertion impossible");
        }
        try {
            filiereService.saveFiliere(f);

            //String niveau = niveauTextField.getText();
            /*if (Licence1RadioButton.isSelected()) {
        String Licence1 = null;
        niveau = Licence1;
        } else {
        if (Licence2RadioButton.isSelected()) {
        String Licence2 = null;
        niveau = Licence2;
        }
        if (Licence3RadioButton.isSelected()) {
        String Licence3 = null;
        niveau = Licence3;
        }
        if (Masteur1RadioButton.isSelected()) {
        String Masteur1 = null;
        niveau = Masteur1;
        }
        if (Masteur2RadioButton.isSelected()) {
        String Masteur2 = null;
        niveau = Masteur2;
        }
        }*/
            if (nomF != null || nomF.isBlank()) {
                JOptionPane.showMessageDialog(null, "insertion Reussie");
            } else {
                JOptionPane.showMessageDialog(null, "insertion impossible");
            }
        } catch (NomFDataInvalid ex) {
            Logger.getLogger(GestionDesFilieres.class.getName()).log(Level.SEVERE, null, ex);
            nomfErrorLabel.setText(ex.getMessage());
            return;
        }

    }//GEN-LAST:event_saveFiliereButtonActionPerformed

    private void Licence1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Licence1RadioButtonActionPerformed
        Masteur2RadioButton.setSelected(true);
        Licence1RadioButton.setSelected(true);
        Licence2RadioButton.setSelected(true);
        Licence3RadioButton.setSelected(true);
        Masteur1RadioButton.setSelected(true);

    }//GEN-LAST:event_Licence1RadioButtonActionPerformed

    private void Licence2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Licence2RadioButtonActionPerformed
        Masteur2RadioButton.setSelected(true);
        Licence1RadioButton.setSelected(true);
        Licence2RadioButton.setSelected(true);
        Licence3RadioButton.setSelected(true);
        Masteur1RadioButton.setSelected(true);

    }//GEN-LAST:event_Licence2RadioButtonActionPerformed

    private void Licence3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Licence3RadioButtonActionPerformed
        Masteur2RadioButton.setSelected(true);
        Licence1RadioButton.setSelected(true);
        Licence2RadioButton.setSelected(true);
        Licence3RadioButton.setSelected(true);
        Masteur1RadioButton.setSelected(true);

    }//GEN-LAST:event_Licence3RadioButtonActionPerformed

    private void ExitFiliereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitFiliereButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitFiliereButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        //String idf = null;
        // String nomF = null;
        /*String idf = idFTextField.getText();
        String nomF = nameTextField.getText();
        if (idf != null && nomF != null) {
            Licence1RadioButton.setSelected(true);
            Licence2RadioButton.setSelected(true);
            Licence3RadioButton.setSelected(true);
            Masteur1RadioButton.setSelected(true);
            Masteur2RadioButton.setSelected(true);
        }*/
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void cancelFiliereButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFiliereButton1ActionPerformed
       nameTextField.setText("");
    }//GEN-LAST:event_cancelFiliereButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitFiliereButton;
    private javax.swing.JRadioButton Licence1RadioButton;
    private javax.swing.JRadioButton Licence2RadioButton;
    private javax.swing.JRadioButton Licence3RadioButton;
    private javax.swing.JRadioButton Masteur1RadioButton;
    private javax.swing.JRadioButton Masteur2RadioButton;
    private javax.swing.JButton cancelFiliereButton1;
    private javax.swing.JButton deleteFiliereButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nomfErrorLabel;
    private javax.swing.JButton saveFiliereButton;
    // End of variables declaration//GEN-END:variables
}
